import jsPDF from 'jspdf';

const PAGE_W = 612;
const PAGE_H = 792;
const MARGIN = 45;
const CONTENT_W = PAGE_W - MARGIN * 2;

const formatCurrency = (val) => {
  if (val === undefined || val === null) return '$0';
  return '$' + Math.round(val).toLocaleString();
};

const USE_CODE_DESCRIPTIONS = {
  "101": "Single Family Residential", "102": "Condo", "104": "Two Family",
  "109": "Multiple Houses", "130": "Vacant Land", "131": "Vacant Land", "132": "Vacant Land",
  "314": "Restaurant/Bar", "316": "Mixed Use", "325": "Motel", "334": "Gas Station",
  "337": "Parking Lot", "340": "General Office", "391": "Vacant Commercial",
  "392": "Vacant Commercial", "013": "Multiple Use", "915": "Gov/Institutional",
  "929": "Gov/Institutional", "930": "Gov/Institutional", "950": "Gov/Institutional",
  "960": "Gov/Institutional", "970": "Gov/Institutional", "971": "Gov/Institutional"
};

function getFieldValue(parcel, key) {
  switch (key) {
    case 'address': return parcel.address || parcel.addr || '';
    case 'street': return parcel.street || '';
    case 'owner': return parcel.owner || '';
    case 'total_val': return formatCurrency(parcel.total_val || parcel.totalVal);
    case 'bldg_val': return formatCurrency(parcel.bldg_val || parcel.bldgVal);
    case 'land_val': return formatCurrency(parcel.land_val || parcel.landVal);
    case 'lot_size': return (parcel.lot_size || parcel.acres || 0).toFixed(2);
    case 'use_code': {
      const code = parcel.use_code || parcel.useCode || '';
      const desc = USE_CODE_DESCRIPTIONS[code];
      return desc ? `${code} (${desc})` : code;
    }
    case 'centroid_lat': return (parcel.centroid_lat || 0).toFixed(6);
    case 'centroid_lon': return (parcel.centroid_lon || 0).toFixed(6);
    default: return '';
  }
}

function getFieldLabel(key, allFields) {
  const f = allFields.find(x => x.key === key);
  return f ? f.label : key;
}

/**
 * Capture the Leaflet map as a data URL using html2canvas-like approach.
 * Falls back to a simple colored rectangle if capture fails.
 */
async function captureMap(mapElement) {
  try {
    // Dynamically import html2canvas
    const { default: html2canvas } = await import('https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.esm.js').catch(() => ({ default: null }));
    if (html2canvas && mapElement) {
      const canvas = await html2canvas(mapElement, {
        useCORS: true, allowTaint: true, scale: 2,
        logging: false, backgroundColor: '#f0f2f5'
      });
      return canvas.toDataURL('image/jpeg', 0.85);
    }
  } catch (e) {
    console.warn('Map capture failed, using placeholder:', e);
  }
  return null;
}

export async function exportBoundaryPDF({ boundary, insideParcels, selectedFields, allFields, stats, userName, mapElement }) {
  const pdf = new jsPDF({ unit: 'pt', format: 'letter' });

  // ── Page 1: Header + Map ──
  let y = MARGIN;

  // Title
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(20);
  pdf.setTextColor(15, 23, 42);
  pdf.text('Southborough DIF Boundary Report', MARGIN, y + 20);
  y += 30;

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.setTextColor(100, 116, 139);
  pdf.text(`Route 9 Corridor District • Generated by ${userName} • ${new Date().toLocaleDateString()}`, MARGIN, y + 12);
  y += 24;

  // Divider
  pdf.setDrawColor(30, 58, 95);
  pdf.setLineWidth(1.5);
  pdf.line(MARGIN, y, MARGIN + CONTENT_W, y);
  y += 16;

  // Stats row
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(11);
  pdf.setTextColor(30, 58, 95);
  const statsText = [
    `Parcels: ${stats.count}`,
    `Assessed: $${(stats.totalAssessed / 1e6).toFixed(1)}M`,
    `Acres: ${stats.totalAcres.toFixed(0)}`,
    `Area: ${stats.areaSqMi.toFixed(2)} sq mi`
  ].join('    •    ');
  pdf.text(statsText, MARGIN, y + 10);
  y += 24;

  // Map capture
  const mapImg = await captureMap(mapElement);
  if (mapImg) {
    const mapH = 320;
    pdf.addImage(mapImg, 'JPEG', MARGIN, y, CONTENT_W, mapH);
    y += mapH + 12;
  } else {
    // Placeholder
    pdf.setFillColor(241, 245, 249);
    pdf.rect(MARGIN, y, CONTENT_W, 200, 'F');
    pdf.setFont('helvetica', 'italic');
    pdf.setFontSize(12);
    pdf.setTextColor(148, 163, 184);
    pdf.text('Map view — open the app to see the interactive boundary', MARGIN + CONTENT_W / 2, y + 100, { align: 'center' });
    y += 212;
  }

  // ── Parcel Table ──

  if (selectedFields.length === 0 || insideParcels.length === 0) {
    // Footer
    addFooter(pdf);
    pdf.save('southborough-dif-boundary.pdf');
    return;
  }

  // Determine column widths
  const headers = selectedFields.map(k => getFieldLabel(k, allFields));
  const colWidth = CONTENT_W / selectedFields.length;
  const ROW_H = 16;
  const HEADER_H = 20;

  // Check if table fits on page 1
  if (y + HEADER_H + 40 > PAGE_H - MARGIN) {
    addFooter(pdf);
    pdf.addPage();
    y = MARGIN;
  }

  // Table title
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(14);
  pdf.setTextColor(15, 23, 42);
  pdf.text(`Parcels Within Boundary (${insideParcels.length})`, MARGIN, y + 14);
  y += 26;

  // Table header
  pdf.setFillColor(30, 58, 95);
  pdf.rect(MARGIN, y, CONTENT_W, HEADER_H, 'F');
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(8);
  pdf.setTextColor(255, 255, 255);
  headers.forEach((h, i) => {
    pdf.text(h, MARGIN + i * colWidth + 4, y + 13, { maxWidth: colWidth - 8 });
  });
  y += HEADER_H;

  // Sort parcels
  const sorted = [...insideParcels].sort((a, b) =>
    ((a.street || '') + (a.address || a.addr || '')).localeCompare((b.street || '') + (b.address || b.addr || ''))
  );

  // Rows
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7);

  sorted.forEach((p, rowIdx) => {
    if (y + ROW_H > PAGE_H - MARGIN - 20) {
      addFooter(pdf);
      pdf.addPage();
      y = MARGIN;

      // Re-draw header
      pdf.setFillColor(30, 58, 95);
      pdf.rect(MARGIN, y, CONTENT_W, HEADER_H, 'F');
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(8);
      pdf.setTextColor(255, 255, 255);
      headers.forEach((h, i) => {
        pdf.text(h, MARGIN + i * colWidth + 4, y + 13, { maxWidth: colWidth - 8 });
      });
      y += HEADER_H;
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(7);
    }

    // Zebra stripe
    if (rowIdx % 2 === 0) {
      pdf.setFillColor(248, 250, 252);
      pdf.rect(MARGIN, y, CONTENT_W, ROW_H, 'F');
    }

    pdf.setTextColor(51, 65, 85);
    selectedFields.forEach((key, i) => {
      const val = getFieldValue(p, key);
      pdf.text(String(val).substring(0, 40), MARGIN + i * colWidth + 4, y + 11, { maxWidth: colWidth - 8 });
    });

    y += ROW_H;
  });

  addFooter(pdf);
  pdf.save('southborough-dif-boundary.pdf');
}

function addFooter(pdf) {
  const pageCount = pdf.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8);
    pdf.setTextColor(148, 163, 184);
    pdf.text(`Page ${i} of ${pageCount}`, PAGE_W / 2, PAGE_H - 25, { align: 'center' });
    pdf.text('Southborough DIF Boundary Editor — googloid.com', PAGE_W / 2, PAGE_H - 15, { align: 'center' });
  }
}
